version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: snclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassftw
    volumes:
     - ./database:/var/lib/postgresql/data

  collector:
    links:
      - db
    depends_on:
      - db
    image: snapcart_clone_collector
    build: ./collector
    volumes:
      - ./collector:/usr/src/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    ## set your startup file here
    command: npm run develop

  # consumer:
  #   image: snapcart_clone_consumer
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000

