version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: snclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassftw
    volumes:
     - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  collector:
    links:
      - db
    depends_on:
      - db
    image: snapcart_clone_collector
    build: ./collector
    volumes:
      - ./collector:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public
      - images:/usr/src/app/images
    env_file:
      - ./collector/.env
    ports:
      - 4000:4000
      - 9229:9229
    ## set your startup file here
    command: npm run develop

  # consumer:
  #   image: snapcart_clone_consumer
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000

volumes: 
  images: